### ISSUE TITLE
Missing controls

### ISSUE THREAD

**Issue by Sneethe** [jorio/Nanosaur2#11]
Running the current V2.1.0 x86-AppImage. 
The following controls as listed on the instructions pdf aren't working.

 -/=  	Raise/Lower the sound volume
 m 		toggle music 
 F1	 	Invoke options dialog at any time
 esc		pause 

I'm not able to verify if the "Toggle Screenshot-safe Pause Mode" works as the instructions says its bound to F15.
Maybe these 5 keybinds could be added to the keyboard controls page? So they can be set to whatever the player wishes.

**Comment by jorio** [comment]
That pdf is the unmodified instruction manual from the 2004 release. I got rid of these keys to streamline the key binding screen:

- -/+: In 2004, not all keyboards had dedicated volume keys; today, you can just use those
- F1: You can access settings from the pause menu
- M: There's a music volume slider in the sound settings
- ESC: That one is still there ;)

Additionally, F9 removes the UI for screenshots.

**Comment by Sneethe** [comment]
Thanks for the clarification. It seems that changed XKB keymaps aren't observed. I use setxkbmap to swap escape and caps lock. Which means no pausing.

**Comment by jorio** [comment]
The game uses scancodes for keyboard input; it only cares about the physical positions of the keys on the keyboard, rather than their value.

This enables the game to work out of the box with international layouts like AZERTY that shuffle letters around compared to QWERTY.

The tradeoff is that the game isn't aware that you have remapped Caps Lock to something else. The pause key isn't rebindable, but your actual Escape key should still work.

**Comment by Sneethe** [comment]
Thank you so much for maintaining these games.

I ended up just using a far lower level approach for my key remaps.
