### ISSUE TITLE
Question - Would you be open to having more localizations?

### ISSUE THREAD

**Issue by CoolCat467** [jorio/Nanosaur2#6]
I was wondering, would you be open for adding more localization from Google Translate? I made a [localization translation utility program](https://github.com/CoolCat467/Localization-Translation-Utility) a while back, and I think with a little bit of modification I could use it to add more supported languages by modifying [strings.csv](https://github.com/jorio/Nanosaur2/tree/master/Data/System/strings.csv).

I am aware that machine translations are usually pretty terrible, but my logic behind adding more even if they are machine translations is that at least they are there, and then at a later date someone who knows the language could just fix the existing bad translation instead of making a new one from scratch, and even if no one changes them, at least the basic idea should be there.

Looking into how `strings.csv` is handled a little bit, it seems that it's hard coded that there is only English, French, German, Spanish, Italian, Swedish, and Dutch. Would it be possible to change this easily, or would it be too much work to add more? If I were to add more translations, what particular languages would be best to add?

Thank you for your time, I love your work keeping these old games alive.

**Comment by jorio** [comment]
I'm more than happy to adapt the game to new languages on a case-by-case basis if someone submits a quality translation.

Unfortunately, adding new translations isn't just a matter of extending the csv file, because the game uses a homemade font system which is currently limited to the 7 languages that ship in the game.

Here are a few examples of random unsupported languages and what needs to be done to support them, ranked from easiest to most difficult:

- Danish: the game's font system already supports all of the letters in their alphabet, except Æ and Ø. We'd have to draw these 2 glyphs and regenerate the font.

- Greek: their alphabet is completely different. First, we'd have to generate a Greek font that fits into the game graphically. Then, we'd have to divide up the font atlas into "pages" and load the pages on demand, so that playing in English (for example) doesn't require keeping the Greek font pages in memory.

- Chinese: separate font like Greek + their writing system has so many different glyphs that it's unpractical to ship them all in the font. We'd have to analyze the translated text and only include the glyphs that are actually used in the game.

- Hebrew: different alphabet + we'd have to redesign the menus to support a right-to-left flow.

- Arabic: same as Hebrew + the built-in font system needs to be reworked to support initial/median/final letter forms.

So, I'm happy to make any of these changes if someone really wants to see their language in the game and submits a handmade translation. But I'm not keen on doing all this work upfront for auto-translated languages.

**Comment by CoolCat467** [comment]
Thank you for the information, I think I'll close this issue as it was for asking the question
